[ci] Implementing a cppcheck job also

diff --git a/.gitlab/ci/code-quality.yml b/.gitlab/ci/code-quality.yml
--- a/.gitlab/ci/code-quality.yml
+++ b/.gitlab/ci/code-quality.yml
@@ -4,6 +4,105 @@ variables:
   REPORTS_PATH: ${CI_PROJECT_DIR}/artifacts/reports
   QUALITY_CHECK_DIR: ci-quality-checks
 
+
+
+.cmake_prep: &cmake_prep |-
+  source ./setup.sh
+  mkdir -p build; cd build
+  echo ${QUALITY_OPTIONS}
+  echo cmake -GNinja -Wno-dev -B${QUALITY_CHECK_DIR} -S. \
+        ${QUALITY_OPTIONS} \
+        ..
+  cmake -GNinja -Wno-dev -B${QUALITY_CHECK_DIR} -S. \
+        ${QUALITY_OPTIONS} \
+        .. \
+        > >(tee ${REPORTS_PATH}/cmake-config.log) \
+        2> >(tee ${REPORTS_PATH}/cmake-config.err >&2)
+
+.quality:
+  image: gitlab-registry.cern.ch/cms-iphc/tk_ph2/dockerimageph2acf
+  tags:
+    - cvmfs
+  stage: quality
+  needs: []
+  allow_failure: true
+  before_script:
+    - echo "Running code quality checks before script"
+    - yum install -y ninja-build iwyu cppcheck jq python3
+    - pip3 install --user --upgrade python-gitlab requests
+    - mkdir -p ${REPORTS_PATH}
+  after_script:
+    - echo "Running code quality checks after script"
+    - ls -l ${CMAKE_DIR}
+    - ls -l ${ARTIFACTS_DIR}/*
+    - ls -l ${REPORTS_PATH}
+  artifacts:
+    paths:
+      - artifacts
+
+# quality:clang-tidy:
+#   extends: .quality
+#   variables:
+#     QUALITY_OPTIONS: -DRUN_TIDY=ON
+#   script:
+#     - echo "Running code quality checks clang-tidy script"
+#     - source /cvmfs/sft.cern.ch/lcg/contrib/clang/${LCG_CLANG_VERSION}/x86_64-centos7/setup.sh || true
+#     - *cmake_prep
+#     - |
+#         cmake --build ${QUALITY_CHECK_DIR} \
+#               > >(tee ${REPORTS_PATH}/clang-tidy.txt) \
+#               2> >(tee ${REPORTS_PATH}/clang-tidy.err >&2) || true
+#     # - popd
+#     # - CLANG_TIDY_EXE=$(dirname $(dirname $(which clang-tidy)))/share/clang/run-clang-tidy.py
+#     # - |
+#     #     ${CLANG_TIDY_EXE} -p ${CMAKE_DIR}/${QUALITY_CHECK_DIR} \
+#     #     -export-fixes ${REPORTS_PATH}/clang-tidy-fixes.yml ${MAKE_OPTIONS} \
+#     #     2> ${REPORTS_PATH}/clang-tidy.err > ${REPORTS_PATH}/clang-tidy.txt || true
+#     #     # -fix -format -style='file'
+
+# quality:clang-format:
+#   extends: .quality
+#   script:
+#     - echo "Running code quality checks clang-format script"
+#     - source /cvmfs/sft.cern.ch/lcg/contrib/clang/${LCG_CLANG_VERSION}/x86_64-centos7/setup.sh || true
+#     - curl -LO https://raw.githubusercontent.com/Sarcasm/run-clang-format/master/run-clang-format.py
+#     - CLANG_FORMAT_EXE=./run-clang-format.py
+#     - chmod +x ${CLANG_FORMAT_EXE}
+#     - export PATCHFILE=clang-format-${GITLAB_USER_LOGIN}-${CI_COMMIT_REF_SLUG}-job-${CI_JOB_ID}.patch
+#     - echo ARTIFACTS_DIR/PATCHFILE is ${ARTIFACTS_DIR}/${PATCHFILE}
+#     - ls -l
+#     - |
+#         git checkout -b patch/${GITLAB_USER_LOGIN}-${CI_COMMIT_REF_SLUG}-job-${CI_JOB_ID}
+#         ${CLANG_FORMAT_EXE} -i -r . || true
+#         ${CLANG_FORMAT_EXE} -i -r . || true
+#         git config --global user.email "${GITLAB_USER_EMAIL}"
+#         git config --global user.name "${GITLAB_USER_NAME}"
+#         git commit -am "Apply clang-format for ${GITLAB_USER_LOGIN}-${CI_COMMIT_REF_SLUG}-job-${CI_JOB_ID}"
+#         git format-patch ${CI_COMMIT_SHORT_SHA} --stdout > ${ARTIFACTS_DIR}/${PATCHFILE}
+#         if [ -s ${ARTIFACTS_DIR}/${PATCHFILE} ]
+#         then
+#           ${CMAKE_DIR}/.gitlab/ci/scripts/post_mr_note.py --fail format
+#         else
+#           ${CMAKE_DIR}/.gitlab/ci/scripts/post_mr_note.py format
+#         fi
+
+## Need an image with cppcheck, or an lcg path therewith
+quality:cppcheck:
+  extends: .quality
+  variables:
+    QUALITY_OPTIONS: -DRUN_CPPCHECK=ON
+  script:
+    - echo "Running code quality checks cppcheck script"
+    - *cmake_prep
+    - |
+        cmake --build ${QUALITY_CHECK_DIR} \
+              > >(tee ${REPORTS_PATH}/cppcheck.txt) \
+              2> >(tee ${REPORTS_PATH}/cppcheck.err >&2) || true
+
+
+
+
+
 # See: https://gitlab.cern.ch/gitlabci-examples/static_code_analysis
 quality:cpplint:
   image: gitlab-registry.cern.ch/computersecurity/security-services-code-checking:latest
